### ISSUE TITLE
Cannot run main.py

### ISSUE THREAD

**Issue by jvgomez** [krishauser/pyOptimalMotionPlanning#1]
Hi,

I have cloned the repo, installed all the dependencies (PyOpenGL_accelerate as well), and using Python 2.7.6 on Ubuntu 14.04 64bit. I run the command:
`python main.py Bugtrap ao-rrt`

And the following error appears:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from pomp.visualizer import runVisualizer
  File "/home/jvgomez/Desktop/pyOptimalMotionPlanning/pomp/visualizer.py", line 1, in <module>
    from klampt.glprogram import GLProgram
  File "/home/jvgomez/Desktop/pyOptimalMotionPlanning/pomp/klampt/glprogram.py", line 10, in <module>
    from OpenGL.GL import *
  File "/usr/lib/python2.7/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python2.7/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/__init__.py", line 19, in <module>
    from OpenGL.arrays.arraydatatype import *
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/arraydatatype.py", line 14, in <module>
    from OpenGL_accelerate.arraydatatype import ArrayDatatype as ADT
  File "arraydatatype.pyx", line 1, in init OpenGL_accelerate.arraydatatype (src/arraydatatype.c:10964)
  File "wrapper.pyx", line 3, in init OpenGL_accelerate.wrapper (src/wrapper.c:11183)
  File "/usr/lib/python2.7/dist-packages/OpenGL/error.py", line 224, in <module>
    ErrorChecker = _ErrorChecker( platform )
  File "errorchecker.pyx", line 17, in OpenGL_accelerate.errorchecker._ErrorChecker.__init__ (src/errorchecker.c:818)
TypeError: __init__() takes at least 2 positional arguments (1 given)
```

What am I doing wrong?

Thanks!

**Comment by krishauser** [comment]
Hi Javier, 

This looks like an PyOpenGL issue. You should be able to import OpenGL.GL without error. I don't think I can help you with this issue, you should contact the authors of that package for more help.

Regards,
Kris Hauser

**Comment by jvgomez** [comment]
Thanks for the reply. Could you please tell me which version of PyOpenGL are you using? Also which operating system and 32b or 64b please. It seems that the PyOpenGL problem is due I am using an older version, but in my specific case I cannot easily update it.
