### ISSUE TITLE
Issue in running main.py

### ISSUE THREAD

**Issue by sparshgarg23** [krishauser/pyOptimalMotionPlanning#4]
Hi,
While executing main.py I ran into the following error
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from pomp.example_problems import *
AttributeError: module 'pomp.example_problems' has no attribute 'lqr'

After looking at the pomp folder I saw that this code depends on klamp,so if I install klamp will the issue go away?

**Comment by sparshgarg23** [comment]
Ok I installed klamp,the issue still persists

**Comment by krishauser** [comment]
Sorry, that was an uncommitted file. Try pulling and see if it's there for you.

**Comment by sparshgarg23** [comment]
Ok it works now,but in controspaces.py we are importing the module differences,but I noticed one thing,while other module imports had a . prefix ,the import differences didn't have the dot.This leads to an error :
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from pomp.planners import allplanners
  File "/home/vkchlt0297/pyOptimalMotionPlanning/pomp/planners/allplanners.py", line 4, in <module>
    from ..spaces.controlspace import *
  File "/home/vkchlt0297/pyOptimalMotionPlanning/pomp/spaces/controlspace.py", line 6, in <module>
    import differences
ModuleNotFoundError: No module named 'differences'
I was wondering if  adding a . over there might fix it .
Update that fixed it,but another module called pomp.planners.optimization is missing.
thanks

**Comment by krishauser** [comment]
Forgot another file in the last push. Please try again.
